### ISSUE TITLE
Code for StackedAutoEncoder is missing

### ISSUE THREAD

**Issue by rootAvish** [eelxpeng/CollaborativeVAE#7]
Hi, thanks for publishing the code along with your paper. Just wanted to point out that the code for the "StackedAutoEncoder" called here: https://github.com/eelxpeng/CollaborativeVAE/blob/master/citeulike-t/test_dae.py#L27 is missing in the lib.

I'm sorry if I missed it while reading your paper, you pretrained using DAE in the case of citeulike-t instead of standard variational autoencoders as in case of citeulike-a?

**Comment by eelxpeng** [comment]
@rootAvish Yes, you're right. I renamed some files when I released the code. Now it is fixed.

**Comment by rootAvish** [comment]
Cool, thanks for the clarification 🙂
